//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Highway.Insurance.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Highway.Insurance.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only valid when the list item is child of a list or a combo box..
        /// </summary>
        internal static string InvalidListItemOperation {
            get {
                return ResourceManager.GetString("InvalidListItemOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protocol {0} is not supported..
        /// </summary>
        internal static string InvalidProtocolForBrokenLinkCheck {
            get {
                return ResourceManager.GetString("InvalidProtocolForBrokenLinkCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout passed is not valid.  The timeout should be &amp;gt; 0 or -1 for using the default timeout..
        /// </summary>
        internal static string InvalidTimeoutForBrokenLinkCheck {
            get {
                return ResourceManager.GetString("InvalidTimeoutForBrokenLinkCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri passed is not an absolute Uri and cannot be validated..
        /// </summary>
        internal static string InvalidUriForBrokenLinkCheck {
            get {
                return ResourceManager.GetString("InvalidUriForBrokenLinkCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control passed is not a list view control.  This operation is valid only for list view control..
        /// </summary>
        internal static string NotAListViewControl {
            get {
                return ResourceManager.GetString("NotAListViewControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control passed is not a list view item control.  This operation is valid only for list view item control..
        /// </summary>
        internal static string NotAListViewItemControl {
            get {
                return ResourceManager.GetString("NotAListViewItemControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list view control is not in report view mode. This operation is valid only in report view mode..
        /// </summary>
        internal static string NotInReportViewMode {
            get {
                return ResourceManager.GetString("NotInReportViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property value is of data type &apos;{0}&apos; which is not comparable..
        /// </summary>
        internal static string ValueIsNotComparable {
            get {
                return ResourceManager.GetString("ValueIsNotComparable", resourceCulture);
            }
        }
    }
}
