// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ExampleTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlCustom uIExampleOneUnorderedCustom = this.UIDCodeFunHighwayHighwWindow.UIFileDCodeFunHighwayHDocument.UIExampleOneUnorderedCustom;
            HtmlCustom uITest1orderedCustom = this.UIDCodeFunHighwayHighwWindow.UIFileDCodeFunHighwayHDocument.UITest1orderedCustom;
            HtmlCustom uITest1orderedCustom1 = this.UIDCodeFunHighwayHighwWindow.UIFileDCodeFunHighwayHDocument.UITest1orderedCustom1;
            #endregion

            // Click 'Example One Unordered' custom control
            Mouse.Click(uIExampleOneUnorderedCustom, new Point(16, 5));

            // Click 'Test 1 ordered' custom control
            Mouse.Click(uITest1orderedCustom, new Point(15, 8));

            // Click 'Test 1 ordered' custom control
            Mouse.Click(uITest1orderedCustom1, new Point(16, 9));
        }
        
        #region Properties
        public UIDCodeFunHighwayHighwWindow UIDCodeFunHighwayHighwWindow
        {
            get
            {
                if ((this.mUIDCodeFunHighwayHighwWindow == null))
                {
                    this.mUIDCodeFunHighwayHighwWindow = new UIDCodeFunHighwayHighwWindow();
                }
                return this.mUIDCodeFunHighwayHighwWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDCodeFunHighwayHighwWindow mUIDCodeFunHighwayHighwWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDCodeFunHighwayHighwWindow : BrowserWindow
    {
        
        public UIDCodeFunHighwayHighwWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIFileDCodeFunHighwayHDocument UIFileDCodeFunHighwayHDocument
        {
            get
            {
                if ((this.mUIFileDCodeFunHighwayHDocument == null))
                {
                    this.mUIFileDCodeFunHighwayHDocument = new UIFileDCodeFunHighwayHDocument(this);
                }
                return this.mUIFileDCodeFunHighwayHDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIFileDCodeFunHighwayHDocument mUIFileDCodeFunHighwayHDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIFileDCodeFunHighwayHDocument : HtmlDocument
    {
        
        public UIFileDCodeFunHighwayHDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "D:/Code/Fun/Highway/Highway.Insurance/Lists.html";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "file://D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html";
            this.WindowTitles.Add("D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIExampleOneUnorderedCustom
        {
            get
            {
                if ((this.mUIExampleOneUnorderedCustom == null))
                {
                    this.mUIExampleOneUnorderedCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIExampleOneUnorderedCustom.SearchProperties["TagName"] = "LI";
                    this.mUIExampleOneUnorderedCustom.SearchProperties["Id"] = null;
                    this.mUIExampleOneUnorderedCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIExampleOneUnorderedCustom.FilterProperties["Class"] = null;
                    this.mUIExampleOneUnorderedCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIExampleOneUnorderedCustom.FilterProperties["InnerText"] = "Example One Unordered";
                    this.mUIExampleOneUnorderedCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIExampleOneUnorderedCustom.WindowTitles.Add("D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html");
                    #endregion
                }
                return this.mUIExampleOneUnorderedCustom;
            }
        }
        
        public HtmlCustom UITest1orderedCustom
        {
            get
            {
                if ((this.mUITest1orderedCustom == null))
                {
                    this.mUITest1orderedCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUITest1orderedCustom.SearchProperties["TagName"] = "LI";
                    this.mUITest1orderedCustom.SearchProperties["Id"] = null;
                    this.mUITest1orderedCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUITest1orderedCustom.FilterProperties["Class"] = null;
                    this.mUITest1orderedCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUITest1orderedCustom.FilterProperties["InnerText"] = "Test 1 ordered";
                    this.mUITest1orderedCustom.FilterProperties["TagInstance"] = "3";
                    this.mUITest1orderedCustom.WindowTitles.Add("D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html");
                    #endregion
                }
                return this.mUITest1orderedCustom;
            }
        }
        
        public HtmlCustom UITest1orderedCustom1
        {
            get
            {
                if ((this.mUITest1orderedCustom1 == null))
                {
                    this.mUITest1orderedCustom1 = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUITest1orderedCustom1.SearchProperties["TagName"] = "LI";
                    this.mUITest1orderedCustom1.SearchProperties["Id"] = null;
                    this.mUITest1orderedCustom1.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUITest1orderedCustom1.FilterProperties["Class"] = null;
                    this.mUITest1orderedCustom1.FilterProperties["ControlDefinition"] = null;
                    this.mUITest1orderedCustom1.FilterProperties["InnerText"] = "Test 1 ordered";
                    this.mUITest1orderedCustom1.FilterProperties["TagInstance"] = "4";
                    this.mUITest1orderedCustom1.WindowTitles.Add("D:\\Code\\Fun\\Highway\\Highway.Insurance\\Lists.html");
                    #endregion
                }
                return this.mUITest1orderedCustom1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIExampleOneUnorderedCustom;
        
        private HtmlCustom mUITest1orderedCustom;
        
        private HtmlCustom mUITest1orderedCustom1;
        #endregion
    }
}
